[project]
name = "substack-extractor"
version = "0.1.0"
description = "Crawls and extracts the text of a URL containing a Substack post"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "playwright>=1.50.0",
]
